name: build-test-deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'  # Updated to use Node.js 20

      - name: Install dependencies
        run: npm install

      - name: Build project
        run: npm run build

  test:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'  # Updated to use Node.js 20

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm test  # Adjust or remove if you don't have test scripts

  deploy:
    needs: test
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pages: write
      id-token: write

    environment:
      name: production
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'  # Updated to use Node.js 20

      - name: Install dependencies
        run: npm install

      - name: Build for deployment
        run: npm run build

      - name: Upload artifacts
        uses: actions/upload-pages-artifact@v1
        with:
          path: "dist"  # Ensure this matches your Vite build output folder

      - name: Deploy
        id: deployment
        uses: actions/deploy-pages@v1
